### PR TITLE
ASP .NET core support

### PR DESCRIPTION
**Pull request by zabulus**
PR submit because I want to share my work, get some feedback. I have doubts that it should be merged as-is.

Things, that left to do:
1. ChameleonForms.Generated project is used for regeneration of DefaultHtmlHelpers and TwitterBootstrapHtmlHelpers. Currently they both are generated via old (not .net core) razorgen and after that manually weaved into new (.net core) way. Need to accomplish this automatically or better to rewrite them for new razorgen.
2. nuget package. Preferable it would be a separate .NS package with ".Core" or "Core" suffix. But it's up to you.
3. Maybe some tests were rewritten in rush to make them green, but rewritten wrong or made them unusable.
4. Maybe some refactoring is needed, specially in unit-tests.
5. CI.

### CODE REVIEW

**Comment by zabulus** [comment]
Commits were squashed. Unsquashed history is here: https://github.com/zabulus/ChameleonForms/tree/aspnet-core.

**Comment by praga** [comment]
Any updates on this?

**Comment by zabulus** [comment]
I'm trying to update it to aspnet core 3, and bring it up in our project. I think in two weeks I'll bring update to this PR

**Comment by praga** [comment]
Tried to use it in a asp.net core 3.0 package and encountered few issues. Please keep me posted.

**Comment by praga** [comment]
Hey mate, just checking on .net core 3.0 migration.

**Comment by zabulus** [comment]
@praga I've updated the PR and associated branch. It works, but still there are plenty of items to fix, described in first message.

**Comment by praga** [comment]
Thanks mate, I'll pull your branch and build it locally and test it. I'll keep you posted if I come into any issues. I am applying it on a fairly big project. It will take us a couple of months to start doing UAT tests to identify bugs.

**Comment by robdmoore** [comment]
Closing this since it's superceded by #162. It's getting really close now :D. Thanks so much for the headstart @zabulus!!

**Comment by robdmoore** [comment]
FYI the full conversion to netcoreapp3.1 is now done and released as 4.0.0-beta0001. Documentation has been fully reviewed and updated. I've poured over pretty much every line of code and the test coverage is better than ever so this is a high quality beta release that is acceptable for production scenarios.

Main thing missing to call it 4.0.0 proper is tag helper support (since I feel that's the idiomatic way of implementing ChameleonForms in .NET Core). The existing methods still work as great as they ever did though (better in fact - .NET Core has allowed for some nice enhancements).

**Pull request closed without merging**
