### PR TITLE
Support List of Tuples

### PR DESCRIPTION
**Pull request by jtheisen**
The commit messages should explain everything.

### CODE REVIEW

**Comment by jtheisen** [comment]
Note to the array thing: `typeof(Tuple<String[]>).GetGenericArguments()` is strangely `String` and not `null` or even `String` - hence the bug.

**Comment by robdmoore** [comment]
Thanks :)

Any chance you can write a test that exposes the bug?

**Comment by jtheisen** [comment]
I should mention that the tests are a bit messed up for me: I'm German and there are some troubles with cultured DateTime rendering and parsing. I fixed some of the issues and for another the `FormatString` attribute usage I commented out (both things uncommited) so that I can run the tests.

**Comment by jtheisen** [comment]
So are you going to put that in? The tests are there, I suppose they will run fine on TeamCity.

**Comment by robdmoore** [comment]
On my todo list

Matt and I have been distracted running the DDD Perth conference over the last few weeks.

**Comment by jtheisen** [comment]
No hurry, just wanted feedback.

**Comment by robdmoore** [comment]
Thanks for the contribution :)

**Pull request merged**
