### PR TITLE
WithoutLabel method does not affect boolean field generation

### PR DESCRIPTION
**Pull request by zabulus**

### CODE REVIEW

**Comment by robdmoore** [comment]
This was kind of a deliberate choice. WithoutLabel is about getting rid of the label in the field template. If you want a way to remove the label attached to a checkbox for a boolean field then I'd suggest creating a new WithoutInlineLabel method (which matches up with the IFieldConfiguration InlineLabel method). Thoughts?

**Comment by zabulus** [comment]
This is the old request. I've found a couple of problems with this implementation. I'll extract logic from my changes and update PR.

**Comment by robdmoore** [comment]
Yep - sorry mate. Recently bought a house so my life has been upturned for the last few months. This one slipped through the cracks!

**Comment by zabulus** [comment]
No problem, we started using a local nuget gallery in our project. So we became independent from such PR delays in open source projects we use.

**Comment by zabulus** [comment]
Ok I've updated the branch. I've added BooleanFieldGenerator, that returns empty pre-label.
Next BooleanHandler will add post-label as it was. WithoutLabel on checkboxes now works as we expected.

**Comment by robdmoore** [comment]
For Boolean fields we deliberately had the Label so I don't really agree with this change.

Are you able to explain what you are trying to achieve with it?

**Comment by zabulus** [comment]
sure
When I write
```C#
@s.FieldFor(x=>x.SomeCheckbox).WithoutLabel()
```
I have such HTML output:
```
<div class="checkbox">
            <input id="SomeCheckbox" name="SomeCheckbox" type="checkbox" value="true"> <label for="SomeCheckbox">Some checkbox</label><em class="required" title="Required">∗</em>

             <span class="field-validation-valid help-block" data-valmsg-for="SomeCheckbox" data-valmsg-replace="true"></span>
            </div>
```

**Comment by robdmoore** [comment]
Cool, so can we instead create a .WithoutInlineLabel() method.

Then you can call that for all boolean fields as part of your custom form template (or later when we add ability to target fields by convention you could do it without needing a custom form template).

To my mind the label with the checkbox is part of the same control and most of the time that's appropriate I would have thought? a checkbox by itself looks weird.,

**Comment by zabulus** [comment]
> a checkbox by itself looks weird.,
In our view, we have a table in form. One of the columns is "Disabled/Enabled", others are "Description", "Name" and so on. So we need in first column just a checkbox without label.
> Then you can call that for all boolean fields
As I thought WithoutLabel should apply to any form field no matter boolean checkbox or textbox.

**Comment by robdmoore** [comment]
Cool - that's a good example. Although, in those circumstances I often still include the label, but set the text to nothing so that you can have a bigger hit area for the checkbox (although in those cases you want to wrap the checkbox in a label rather than having it separate so you would still want to hide the in-built checkbox). That's a pretty specific example though and so I'm even happier that an explicit method on field configuration makes sense.

`WithoutLabel` is about hiding the [field label](https://github.com/MRCollective/ChameleonForms/wiki/field-label) that shows up as part of the [field](https://github.com/MRCollective/ChameleonForms/wiki/field). The label that appears with the [checkbox](https://github.com/MRCollective/ChameleonForms/wiki/boolean) is part of the checkbox [field element](https://github.com/MRCollective/ChameleonForms/wiki/field-element) and so it doesn't make sense for you to hide it with `WithoutLabel`. Further to that, I have had situations where I want to hide the field label, but leave the label that is part of the checkbox field element. Hence why I have suggested a separate `WithoutInlineLabel` method.

Does that make more sense?

**Comment by zabulus** [comment]
I see the point. 
Implemented as sugested: https://github.com/MRCollective/ChameleonForms/pull/118

**Pull request closed without merging**
