### PR TITLE
Fix for bootstrap checkbox bug

### PR DESCRIPTION
**Pull request by jtheisen**
This is a fix for #103.

It works by generating inline labels in the form

```
<label><input>label</label>
```

rather than

```
<input><label>label</label>
```

*always* - even with the default form template. This means I had to change a lot of the approved html.

A fix that wouldn't require the default generated html to be changed would require an additional styling method for radio buttons and checkboxes on `IFormTemplate`.

In any case, that label syntax is one of the two legitimate usages for the label element.

All tests run fine except those which I'm sure only don't run fine because of my locale problems.

The pull request contains an updated bootstrap.

One minor thing: When a checkbox field has no label (`.WithoutInlineLabel()`), then the bug still manifests. I guess this isn't something bootstrap users would do though, as they would then have no label at all.

### CODE REVIEW

**Comment by jtheisen** [comment]
Hmm, just saw that I didn't base this change request off your master but mine. That wasn't quite intentional, but I guess it shouldn't matter.

**Comment by robdmoore** [comment]
Somewhat confusingly the commits for the list of tuples support are still in here even though I merged the other PR. Can you rebase your branch to remove those commits?

My only concern with merging this PR is it's a breaking change in terms of the HTML - It's entirely possible it will break some people's styling. Thoughts @MattDavies?

**Comment by jtheisen** [comment]
Will do the rebase, I will need until later this evening though.

**Comment by jtheisen** [comment]
There would also be the option of making the new inline label output change optional by introducing some configuration option.

It may not be nice to have two html outputs in parallel, but one has to way that against the breaking change.

Regardless of which output would then be the default, there's the question of how to inform users about there being two options.

**Comment by robdmoore** [comment]
To be honest, I think I'd prefer that there is a configuration option and that the default is the current way, but the Twitter Bootstrap Form Template sets it to wrap.

We can add it as an option to IFieldConfiguration. Maybe .InlineLabelWrapsElement() or something like that?

As to informing users, that's simply a matter of adding to the wiki or letting people discover it with intellisense by dotting off of something that returns IFieldConfiguration.

**Pull request closed without merging**
